[WIP] Improved CPU bus implementation
Cyuubi/LemonLime pull request #13
Opened 2018-09-22 22:33 UTC by Wolfvak

TODO:

- Test absolutely everything

- Make sure everything is endian-independent (not completely sure how C# handles those cases)

- Move ITCM/DTCM to the ARM9 core and the MPCore PMR to the ARM11 core

- Add WriteUInt16/WriteUInt8 operations that don't rely on RMW

- Better memory mapped peripheral support (parent bus, update on tick, etc)

- Anything else I forgot about

2018-09-23 01:02 UTC, dd01da0465b4542f8f8af4ecedc149ed requested changes

2018-09-23 01:02 UTC, dd01da0465b4542f8f8af4ecedc149ed commented on LemonLime.LLE/CPUBus.cs
> +            return (ushort)(ReadUInt32(MaskAddr) >> (int)((Address - MaskAddr)*8));
Code styling: Please make `return (ushort)(ReadUInt32(MaskAddr) >> (int)((Address - MaskAddr)*8));` `return (ushort)(ReadUInt32(MaskAddr) >> (int)((Address - MaskAddr) * 8));`

2018-09-23 01:02 UTC, dd01da0465b4542f8f8af4ecedc149ed commented on LemonLime.LLE/CPUBus.cs
> +            return (byte)(ReadUInt32(MaskAddr) >> (int)((Address - MaskAddr)*8));
Code styling: Please make `return (byte)(ReadUInt32(MaskAddr) >> (int)((Address - MaskAddr)*8));` `return (byte)(ReadUInt32(MaskAddr) >> (int)((Address - MaskAddr) * 8));`

2018-09-23 01:02 UTC, dd01da0465b4542f8f8af4ecedc149ed commented on LemonLime.LLE/CPUBus.cs
> +            CPUMap Map = BusMap.Where(map => Address >= map.Start && Address <= map.End).SingleOrDefault();
Code styling: Make `map` `FMap`

2018-09-23 01:02 UTC, dd01da0465b4542f8f8af4ecedc149ed commented on LemonLime.LLE/CPUBus.cs
> +                this.Start = Start;
Make this `Base`?

2018-09-23 01:02 UTC, dd01da0465b4542f8f8af4ecedc149ed commented on LemonLime.LLE/CPUBus.cs
> +                this.End = End;
Make this `Size`?

2018-09-23 01:02 UTC, Cyuubi commented on LemonLime.LLE/CPUBus.cs
> +            public uint Start, End;
Code styling: Space between public definition

2018-09-23 01:02 UTC, Cyuubi commented on LemonLime.LLE/CPUDevice.cs
> +    	private uint[] RAM;
Code styling: Space between public definition

2018-09-23 01:02 UTC, Cyuubi commented on LemonLime.LLE/CPUDevice.cs
> +    	private byte[] ROM;
Code styling: Space between public definition

2018-09-23 01:05 UTC, Wolfvak commented on LemonLime.LLE/CPUBus.cs
> +                this.End = End;
No, `Size` implies, well, size. These variables indicate a range, so `Start` and `End` are more accurate, at least more than `Size`.

2018-09-23 01:05 UTC, Cyuubi commented on LemonLime.LLE/CPUBus.cs
> +                this.End = End;
Ah, alright!

2018-09-23 01:06 UTC, Cyuubi commented
Might wanna make the 2 spaces 4 spaces in the code :P

2018-09-23 01:12 UTC, Wolfvak commented
Yeah, Sublime is being dumb and doesn't know whether it should default to spaces or tabs for some reason, so everything looks off when pushed. Will fix later, but right now the technical aspect takes priority over anything else.

About the implementation of WriteUInt8/WriteUInt16, I'm having some second thoughts. On one hand you get the core running faster because there's no need for Read-Modify-Write and the hardware emulation becomes more flexible (very important with some peripherals), but it can potentially lead to a lot of code repetition.

I'll implement it anyway, just putting my thoughts out there.

2018-12-26 00:31 UTC, dd01da0465b4542f8f8af4ecedc149ed approved these changes

2018-12-26 00:33 UTC, merged